apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-alpha-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: service-alpha-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: service-alpha
        property: username
    - secretKey: password
      remoteRef:
        key: service-alpha
        property: password
