apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: service-alpha-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "homelab/service-alpha/config"
        objectType: "secretsmanager"
        jmesPath:
          - path: api_key
            objectAlias: api_key
          - path: db_password
            objectAlias: db_password
  secretObjects:
    - secretName: service-alpha-secret
      type: Opaque
      data:
        - objectName: api_key
          key: api_key
        - objectName: db_password
          key: db_password
